openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Customer care application"
paths:
  /customer-care/customer:
    post:
      tags:
        - Private
      summary: "Inserisce nuovo customer"
      operationId: "inserisciCustomer"
      parameters:
        - name: "input"
          in: query
          description: "input dto per inserire customer"
          required: true
          schema:
            $ref: "#/components/schemas/InserimentoCustomerRequest"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"
  /customer-care/modifica/customer/{codiceFiscale}:
    patch:
      tags:
        - Private
      summary: "Modifica dell' indirizzo del customer"
      operationId: "modificaIndirizzoCustomer"
      parameters:
        - name: codiceFiscale
          description: codice fiscale del customer
          in: path
          required: true
          schema:
            type: string
        - name: customerRequest
          in: query
          description: "Customer"
          required: true
          schema:
            $ref: "#/definitions/CustomerRequest"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"
  /customer-care/modifica/device/{uuid}:
    patch:
      tags:
        - Private
      summary: "Modifica lo stato del device"
      operationId: "modificaStatoDevice"
      parameters:
        - name: uuid
          description: uuid del device
          in: path
          required: true
          schema:
            type: string
        - name: deviceRequest
          in: query
          description: "Device"
          required: true
          schema:
            $ref: "#/definitions/DeviceRequest"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"

components:
  schemas:
    InserimentoCustomerRequest:
      type: object
      required:
        - nome
        - cognome
        - codiceFiscale
        - indirizzo
      properties:
        nome:
          type: string
        cognome:
          type: string
        codiceFiscale:
          type: string
        indirizzo:
          type: string
        devices:
          type: "array"
          items:
            $ref: '#/components/schemas/DeviceDTO'
            #type: string
            #format: uuid
    CustomerResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        message:
          type: string
    DeviceDTO:
      type: object
      properties:
        stato:
          type: string
        uuid:
          type: string
    CustomerRequest:
      type: object
      properties:
        indirizzo:
          type: string
    DeviceRequest:
      type: object
      properties:
        stato:
          type: string
